//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_Campaign
    {
        public KH_Campaign()
        {
            this.Map_Categories_Project = new HashSet<Map_Categories_Project>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public string Partner { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> BrandId { get; set; }
    
        public virtual DM_Brand DM_Brand { get; set; }
        public virtual ICollection<Map_Categories_Project> Map_Categories_Project { get; set; }
        public virtual KH_Customer KH_Customer { get; set; }
    }
}
