//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_Categories_Project
    {
        public int Id { get; set; }
        public Nullable<int> CategorieId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual DM_Categories DM_Categories { get; set; }
        public virtual KH_Campaign KH_Campaign { get; set; }
    }
}
